name: CI

on:
  push:
    branches: ['**']
    tags: ['v*']
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Build Dependencies
        run: |
          brew install libvncserver
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
          cmake --install .
      - name: Package Artifacts
        run: |
          cd build
          zip -r macVNC.app.zip macVNC.app
          # Ensure standalone utility is present
          test -f listwindows && echo "listwindows present" || (echo "listwindows missing" && exit 1)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macVNC-dist
          path: |
            build/macVNC.app.zip
            build/listwindows

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: macVNC-dist
          path: dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/macVNC.app.zip
            dist/listwindows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
