name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Build Dependencies
        run: |
          brew install libvncserver
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cmake --install .
      - name: Archive App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: macVNC App Bundle
          path: build/*.app
